# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
# See https://docs.rubocop.org/en/stable/

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/MethodParameterName:
  AllowedNames: ['as', 'id']

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Exclude:
    - spec/**/*_spec.rb
    - lib/jimmy/schema/**/*.rb

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
